### ISSUE TITLE
ttnv3 branch links /etc/init.d/ssh_tunnel to /var/config/init.d, but file is still in old location

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#86]
The TTNv3 branch links `/etc/init.d/ssh_tunnel` to `/var/config/init.d/ssh_tunnel.init`. But the file is not placed there, it's placed at `/var/config/ssh_tunnel.init`.  The simple fix is to revert the location back to `/var/config`, even though it's counter-intuitive.

**Comment by jchonig** [comment]
Fixed by https://github.com/IthacaThings/ttn-multitech-cm/commit/a1a190394d4f2973ea86aa4b27d6e1cabca8df05

**Comment by terrillmoore** [comment]
Please don't change the location of `/var/config/ssh_tunnel.init` to `/var/config/ssh_tunnel.init`. This will give me a hybrid fleet of systems. The location change is nice, but doesn't add functionality. I can't do a mass `make apply` to change the gateways because gateways come and go; and I frequently have to manually fix gateways because jffs2 clobbers the links (don't know why). My preferred change would be to revert the location change, or make it something that can be backed out on an organization basis.

**Comment by terrillmoore** [comment]
Head of `ttnv3` is still broken. Ignore 2bc5569, but please look at 10d4aa8, as something like this is needed.

**Comment by jchonig** [comment]
Thanks for the fix
